import {
  BusinessType,
  DisplayPlaced,
  ProductColor,
} from "@/generated/prisma/enums";

export const brands = [
  { id: 1, name: "Midea" },
  { id: 2, name: "General Electronics" },
  { id: 3, name: "DEXP" },
  { id: 4, name: "Körting" },
  { id: 5, name: "Schaub Lorenz" },
];

export const series = [
  { id: 1, name: "BCD345" },
  { id: 2, name: "BCD385" },
  { id: 3, name: "BCD405" },
  { id: 4, name: "BCD445" },
  { id: 5, name: "BCD335" },
  { id: 6, name: "BCD375" },
];

export const products = [
  // 345
  {
    id: 1,
    name: "MDRB471MGF01O",
    color: ProductColor.WHITE,
    displayPlaced: DisplayPlaced.ON_DOOR,
    businessType: BusinessType.OBM,
    brandId: 1,
    seriesId: 1,
  },
  {
    id: 2,
    name: "MDRB471MGF33O",
    color: ProductColor.BEIGE,
    displayPlaced: DisplayPlaced.ON_DOOR,
    businessType: BusinessType.OBM,
    brandId: 1,
    seriesId: 1,
  },
  {
    id: 3,
    name: "MDRB471MGF46O",
    color: ProductColor.INOX,
    displayPlaced: DisplayPlaced.ON_DOOR,
    businessType: BusinessType.OBM,
    brandId: 1,
    seriesId: 1,
  },
  {
    id: 4,
    name: "MDRB472MGF01OM",
    color: ProductColor.WHITE,
    displayPlaced: DisplayPlaced.ON_DOOR,
    businessType: BusinessType.OBM,
    brandId: 1,
    seriesId: 1,
  },
  {
    id: 5,
    name: "MDRB472MGF33OM",
    color: ProductColor.BEIGE,
    displayPlaced: DisplayPlaced.ON_DOOR,
    businessType: BusinessType.OBM,
    brandId: 1,
    seriesId: 1,
  },
  {
    id: 6,
    name: "MDRB472MGF46OM",
    color: ProductColor.INOX,
    displayPlaced: DisplayPlaced.ON_DOOR,
    businessType: BusinessType.OBM,
    brandId: 1,
    seriesId: 1,
  },
  {
    id: 7,
    name: "MDRB473MGF01OM",
    color: ProductColor.WHITE,
    displayPlaced: DisplayPlaced.ON_DOOR,
    businessType: BusinessType.OBM,
    brandId: 1,
    seriesId: 1,
  },
  {
    id: 8,
    name: "MDRB473MGF46OM",
    color: ProductColor.INOX,
    displayPlaced: DisplayPlaced.ON_DOOR,
    businessType: BusinessType.OBM,
    brandId: 1,
    seriesId: 1,
  },
  {
    id: 9,
    name: "MDRB469MGF01I",
    color: ProductColor.WHITE,
    displayPlaced: DisplayPlaced.INSIDE,
    businessType: BusinessType.OBM,
    brandId: 1,
    seriesId: 1,
  },
  {
    id: 10,
    name: "MDRB469MGF46I",
    color: ProductColor.INOX,
    displayPlaced: DisplayPlaced.INSIDE,
    businessType: BusinessType.OBM,
    brandId: 1,
    seriesId: 1,
  },
  // 385
  {
    id: 11,
    name: "MDRB522MGE01OD",
    color: ProductColor.WHITE,
    displayPlaced: DisplayPlaced.ON_DOOR,
    businessType: BusinessType.OBM,
    brandId: 1,
    seriesId: 2,
  },
  {
    id: 12,
    name: "MDRB522MGE33OD",
    color: ProductColor.BEIGE,
    displayPlaced: DisplayPlaced.ON_DOOR,
    businessType: BusinessType.OBM,
    brandId: 1,
    seriesId: 2,
  },
  {
    id: 13,
    name: "MDRB522MGE45OD",
    color: ProductColor.BLACK,
    displayPlaced: DisplayPlaced.ON_DOOR,
    businessType: BusinessType.OBM,
    brandId: 1,
    seriesId: 2,
  },
  {
    id: 14,
    name: "MDRB522MGE46OD",
    color: ProductColor.INOX,
    displayPlaced: DisplayPlaced.ON_DOOR,
    businessType: BusinessType.OBM,
    brandId: 1,
    seriesId: 2,
  },
  {
    id: 15,
    name: "MDRB523MGE01ODM",
    color: ProductColor.WHITE,
    displayPlaced: DisplayPlaced.ON_DOOR,
    businessType: BusinessType.OBM,
    brandId: 1,
    seriesId: 2,
  },
  {
    id: 16,
    name: "MDRB523MGE028DM",
    color: ProductColor.BLACK,
    displayPlaced: DisplayPlaced.ON_DOOR,
    businessType: BusinessType.OBM,
    brandId: 1,
    seriesId: 2,
  },
  {
    id: 17,
    name: "MDRB523MGE033DM",
    color: ProductColor.BEIGE,
    displayPlaced: DisplayPlaced.ON_DOOR,
    businessType: BusinessType.OBM,
    brandId: 1,
    seriesId: 2,
  },
  {
    id: 18,
    name: "MDRB523MGE046DM",
    color: ProductColor.INOX,
    displayPlaced: DisplayPlaced.ON_DOOR,
    businessType: BusinessType.OBM,
    brandId: 1,
    seriesId: 2,
  },
];

// export const colors = [
//   { id: 1, name: "White", atribute: "01" },
//   { id: 2, name: "Black", atribute: "28" },
//   { id: 3, name: "Beige", atribute: "33" },
//   { id: 4, name: "Basalt Gray", atribute: "45" },
//   { id: 5, name: "Inox", atribute: "46" },
// ];
