import {
  BusinessType,
  DisplayPlaced,
  ProductColor,
  SeriesAttr,
} from "@/generated/prisma/enums";

export const brands = [
  { id: 1, name: "Midea" },
  { id: 2, name: "General Electronics" },
  { id: 3, name: "DEXP" },
  { id: 4, name: "Körting" },
  { id: 5, name: "Schaub Lorenz" },
  { id: 6, name: "Kuppersberg" },
  { id: 7, name: "Weissgauff" },
  { id: 8, name: "Comfee" },
  { id: 9, name: "HOME" },
];

export const series = [
  { id: 1, name: "BCD345" },
  { id: 2, name: "BCD385" },
  { id: 3, name: "BCD405" },
  { id: 4, name: "BCD445" },
  { id: 5, name: "BCD335" },
  { id: 6, name: "BCD375" },
];

export const products = [
  // 345
  {
    id: 1,
    name: "MDRB471MGF01O",
    seriesAttr: SeriesAttr.CE_BCD345WE_ST,
    color: ProductColor.WHITE,
    displayPlaced: DisplayPlaced.ON_DOOR,
    businessType: BusinessType.OBM,
    brandId: 1,
    seriesId: 1,
  },
  {
    id: 2,
    name: "MDRB471MGF33O",
    seriesAttr: SeriesAttr.CE_BCD345WE_ST,
    color: ProductColor.BEIGE,
    displayPlaced: DisplayPlaced.ON_DOOR,
    businessType: BusinessType.OBM,
    brandId: 1,
    seriesId: 1,
  },
  {
    id: 3,
    name: "MDRB471MGF46O",
    seriesAttr: SeriesAttr.CE_BCD345WE_ST,
    color: ProductColor.INOX,
    displayPlaced: DisplayPlaced.ON_DOOR,
    businessType: BusinessType.OBM,
    brandId: 1,
    seriesId: 1,
  },
  {
    id: 4,
    name: "MDRB472MGF01OM",
    seriesAttr: SeriesAttr.CE_BCD345WE_ST,
    color: ProductColor.WHITE,
    displayPlaced: DisplayPlaced.ON_DOOR,
    businessType: BusinessType.OBM,
    brandId: 1,
    seriesId: 1,
  },
  {
    id: 5,
    name: "MDRB472MGF33OM",
    seriesAttr: SeriesAttr.CE_BCD345WE_ST,
    color: ProductColor.BEIGE,
    displayPlaced: DisplayPlaced.ON_DOOR,
    businessType: BusinessType.OBM,
    brandId: 1,
    seriesId: 1,
  },
  {
    id: 6,
    name: "MDRB472MGF46OM",
    seriesAttr: SeriesAttr.CE_BCD345WE_ST,
    color: ProductColor.INOX,
    displayPlaced: DisplayPlaced.ON_DOOR,
    businessType: BusinessType.OBM,
    brandId: 1,
    seriesId: 1,
  },
  {
    id: 7,
    name: "MDRB473MGF01OM",
    seriesAttr: SeriesAttr.CE_BCD345WE_ST,
    color: ProductColor.WHITE,
    displayPlaced: DisplayPlaced.ON_DOOR,
    businessType: BusinessType.OBM,
    brandId: 1,
    seriesId: 1,
  },
  {
    id: 8,
    name: "MDRB473MGF46OM",
    seriesAttr: SeriesAttr.CE_BCD345WE_ST,
    color: ProductColor.INOX,
    displayPlaced: DisplayPlaced.ON_DOOR,
    businessType: BusinessType.OBM,
    brandId: 1,
    seriesId: 1,
  },
  {
    id: 9,
    name: "MDRB469MGF01I",
    seriesAttr: SeriesAttr.CE_BCD345WE1_ST,
    color: ProductColor.WHITE,
    displayPlaced: DisplayPlaced.INSIDE,
    businessType: BusinessType.OBM,
    brandId: 1,
    seriesId: 1,
  },
  {
    id: 10,
    name: "MDRB469MGF46I",
    seriesAttr: SeriesAttr.CE_BCD345WE1_ST,
    color: ProductColor.INOX,
    displayPlaced: DisplayPlaced.INSIDE,
    businessType: BusinessType.OBM,
    brandId: 1,
    seriesId: 1,
  },
  // 385
  {
    id: 11,
    name: "MDRB522MGE01OD",
    seriesAttr: SeriesAttr.CE_BCD385WX1_JT,
    color: ProductColor.WHITE,
    displayPlaced: DisplayPlaced.ON_DOOR,
    businessType: BusinessType.OBM,
    brandId: 1,
    seriesId: 2,
  },
  {
    id: 12,
    name: "MDRB522MGE33OD",
    seriesAttr: SeriesAttr.CE_BCD385WX1_JT,
    color: ProductColor.BEIGE,
    displayPlaced: DisplayPlaced.ON_DOOR,
    businessType: BusinessType.OBM,
    brandId: 1,
    seriesId: 2,
  },
  {
    id: 13,
    name: "MDRB522MGE45OD",
    seriesAttr: SeriesAttr.CE_BCD385WX1_JT,
    color: ProductColor.BLACK,
    displayPlaced: DisplayPlaced.ON_DOOR,
    businessType: BusinessType.OBM,
    brandId: 1,
    seriesId: 2,
  },
  {
    id: 14,
    name: "MDRB522MGE46OD",
    seriesAttr: SeriesAttr.CE_BCD385WX1_JT,
    color: ProductColor.INOX,
    displayPlaced: DisplayPlaced.ON_DOOR,
    businessType: BusinessType.OBM,
    brandId: 1,
    seriesId: 2,
  },
  {
    id: 15,
    name: "MDRB523MGE01ODM",
    seriesAttr: SeriesAttr.CE_BCD385WX1_JT,
    color: ProductColor.WHITE,
    displayPlaced: DisplayPlaced.ON_DOOR,
    businessType: BusinessType.OBM,
    brandId: 1,
    seriesId: 2,
  },
  {
    id: 16,
    name: "MDRB523MGE28ODM",
    seriesAttr: SeriesAttr.CE_BCD385WX1_JT,
    color: ProductColor.BLACK,
    displayPlaced: DisplayPlaced.ON_DOOR,
    businessType: BusinessType.OBM,
    brandId: 1,
    seriesId: 2,
  },
  {
    id: 17,
    name: "MDRB523MGE33ODM",
    seriesAttr: SeriesAttr.CE_BCD385WX1_JT,
    color: ProductColor.BEIGE,
    displayPlaced: DisplayPlaced.ON_DOOR,
    businessType: BusinessType.OBM,
    brandId: 1,
    seriesId: 2,
  },
  {
    id: 18,
    name: "MDRB523MGE46ODM",
    seriesAttr: SeriesAttr.CE_BCD385WX1_JT,
    color: ProductColor.INOX,
    displayPlaced: DisplayPlaced.ON_DOOR,
    businessType: BusinessType.OBM,
    brandId: 1,
    seriesId: 2,
  },
  {
    id: 19,
    name: "MDRB524MGE01ODM",
    seriesAttr: SeriesAttr.CE_BCD385WX1_JT,
    color: ProductColor.WHITE,
    displayPlaced: DisplayPlaced.ON_DOOR,
    businessType: BusinessType.OBM,
    brandId: 1,
    seriesId: 2,
  },
  {
    id: 20,
    name: "MDRB524MGE28ODM",
    seriesAttr: SeriesAttr.CE_BCD385WX1_JT,
    color: ProductColor.BLACK,
    displayPlaced: DisplayPlaced.ON_DOOR,
    businessType: BusinessType.OBM,
    brandId: 1,
    seriesId: 2,
  },
  {
    id: 21,
    name: "MDRB524MGE46ODM",
    seriesAttr: SeriesAttr.CE_BCD385WX1_JT,
    color: ProductColor.INOX,
    displayPlaced: DisplayPlaced.ON_DOOR,
    businessType: BusinessType.OBM,
    brandId: 1,
    seriesId: 2,
  },
  {
    id: 22,
    name: "MDRB519MGE01ID",
    seriesAttr: SeriesAttr.CE_BCD385WX2_JT,
    color: ProductColor.WHITE,
    displayPlaced: DisplayPlaced.INSIDE,
    businessType: BusinessType.OBM,
    brandId: 1,
    seriesId: 2,
  },
  {
    id: 23,
    name: "MDRB519MGE46ID",
    seriesAttr: SeriesAttr.CE_BCD385WX2_JT,
    color: ProductColor.INOX,
    displayPlaced: DisplayPlaced.INSIDE,
    businessType: BusinessType.OBM,
    brandId: 1,
    seriesId: 2,
  },
  // 405
  {
    id: 24,
    name: "MDRB548MMF01",
    seriesAttr: SeriesAttr.CE_BCD405WX_JQ,
    color: ProductColor.WHITE,
    displayPlaced: DisplayPlaced.INSIDE,
    businessType: BusinessType.OBM,
    brandId: 1,
    seriesId: 3,
  },
  {
    id: 25,
    name: "MDRB548MMF46",
    seriesAttr: SeriesAttr.CE_BCD405WX_JQ,
    color: ProductColor.STEEL_GRAY,
    displayPlaced: DisplayPlaced.INSIDE,
    businessType: BusinessType.OBM,
    brandId: 1,
    seriesId: 3,
  },
  // 445
  {
    id: 26,
    name: "MDRB600MMF01",
    seriesAttr: SeriesAttr.CE_BCD445WX_JQ,
    color: ProductColor.WHITE,
    displayPlaced: DisplayPlaced.INSIDE,
    businessType: BusinessType.OBM,
    brandId: 1,
    seriesId: 4,
  },
  {
    id: 27,
    name: "MDRB600MMF46",
    seriesAttr: SeriesAttr.CE_BCD445WX_JQ,
    color: ProductColor.STEEL_GRAY,
    displayPlaced: DisplayPlaced.INSIDE,
    businessType: BusinessType.OBM,
    brandId: 1,
    seriesId: 4,
  },
  // 335
  {
    id: 28,
    name: "MDRB457FGF01ID",
    seriesAttr: SeriesAttr.CE_BCD335WX_JQ,
    color: ProductColor.WHITE,
    displayPlaced: DisplayPlaced.INSIDE,
    businessType: BusinessType.OBM,
    brandId: 1,
    seriesId: 5,
  },
  {
    id: 29,
    name: "MDRB457FGF33ID",
    seriesAttr: SeriesAttr.CE_BCD335WX_JQ,
    color: ProductColor.BEIGE,
    displayPlaced: DisplayPlaced.INSIDE,
    businessType: BusinessType.OBM,
    brandId: 1,
    seriesId: 5,
  },
  {
    id: 30,
    name: "MDRB457FGF46ID",
    seriesAttr: SeriesAttr.CE_BCD335WX_JQ,
    color: ProductColor.INOX,
    displayPlaced: DisplayPlaced.INSIDE,
    businessType: BusinessType.OBM,
    brandId: 1,
    seriesId: 5,
  },
  {
    id: 31,
    name: "MDRB458FGF01IDM",
    seriesAttr: SeriesAttr.CE_BCD335WX_JQ,
    color: ProductColor.WHITE,
    displayPlaced: DisplayPlaced.INSIDE,
    businessType: BusinessType.OBM,
    brandId: 1,
    seriesId: 5,
  },
  {
    id: 32,
    name: "MDRB458FGF33IDM",
    seriesAttr: SeriesAttr.CE_BCD335WX_JQ,
    color: ProductColor.BEIGE,
    displayPlaced: DisplayPlaced.INSIDE,
    businessType: BusinessType.OBM,
    brandId: 1,
    seriesId: 5,
  },
  {
    id: 33,
    name: "MDRB458FGF46IDM",
    seriesAttr: SeriesAttr.CE_BCD335WX_JQ,
    color: ProductColor.INOX,
    displayPlaced: DisplayPlaced.INSIDE,
    businessType: BusinessType.OBM,
    brandId: 1,
    seriesId: 5,
  },
  // 375
  {
    id: 34,
    name: "MDRB509FGF01ID",
    seriesAttr: SeriesAttr.CE_BCD375WX_JQ,
    color: ProductColor.WHITE,
    displayPlaced: DisplayPlaced.INSIDE,
    businessType: BusinessType.OBM,
    brandId: 1,
    seriesId: 6,
  },
  {
    id: 35,
    name: "MDRB509FGF33ID",
    seriesAttr: SeriesAttr.CE_BCD375WX_JQ,
    color: ProductColor.BEIGE,
    displayPlaced: DisplayPlaced.INSIDE,
    businessType: BusinessType.OBM,
    brandId: 1,
    seriesId: 6,
  },
  {
    id: 36,
    name: "MDRB509FGF46ID",
    seriesAttr: SeriesAttr.CE_BCD375WX_JQ,
    color: ProductColor.INOX,
    displayPlaced: DisplayPlaced.INSIDE,
    businessType: BusinessType.OBM,
    brandId: 1,
    seriesId: 6,
  },
  {
    id: 37,
    name: "MDRB510FGF01IDM",
    seriesAttr: SeriesAttr.CE_BCD375WX_JQ,
    color: ProductColor.WHITE,
    displayPlaced: DisplayPlaced.INSIDE,
    businessType: BusinessType.OBM,
    brandId: 1,
    seriesId: 6,
  },
  {
    id: 38,
    name: "MDRB510FGF33IDM",
    seriesAttr: SeriesAttr.CE_BCD375WX_JQ,
    color: ProductColor.BEIGE,
    displayPlaced: DisplayPlaced.INSIDE,
    businessType: BusinessType.OBM,
    brandId: 1,
    seriesId: 6,
  },
  {
    id: 39,
    name: "MDRB510FGF46IDM",
    seriesAttr: SeriesAttr.CE_BCD375WX_JQ,
    color: ProductColor.INOX,
    displayPlaced: DisplayPlaced.INSIDE,
    businessType: BusinessType.OBM,
    brandId: 1,
    seriesId: 6,
  },
];

export const items = [
  {
    id: 1,
    name: "Color masterbatch",
    nameExt: "White",
    attr: "RE-WH101",
    isMaterial: true,
  },
  {
    id: 2,
    name: "Color masterbatch",
    nameExt: "Transparent Light Gray",
    attr: "RE-GY901",
    isMaterial: true,
  },
];

export const itemCodes = [
  { id: 1, code: "10403002001668", itemId: 1 },
  { id: 2, code: "10403002001546", itemId: 1 },
  { id: 3, code: "10403002001556", itemId: 1 },
  { id: 4, code: "10403002001543", itemId: 1 },
  { id: 5, code: "10403002006811", itemId: 2 },
];
